<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>i3 FAQ - Individual question feed</title><link>https://faq.i3wm.org/questions/</link><description>Frequently asked questions and answers about the i3 window manager</description><atom:link href="http://faq.i3wm.org/feeds/question/4624/" rel="self"></atom:link><language>en</language><copyright>Copyright i3, 2012</copyright><lastBuildDate>Thu, 25 Sep 2014 07:20:24 +0000</lastBuildDate><item><title>Switching from unity to i3 causes a problem with a python package</title><link>https://faq.i3wm.org/question/4624/switching-from-unity-to-i3-causes-a-problem-with-a-python-package/</link><description>I have used virtualenv to create a local installation of python and some packages(numpy) are bound to some shared object (OpenBlas) compiled and linked locally. It works perfectly when I use unity in ubuntu 14.04 but when I switch to i3 I receive this error message:

&gt;  from numpy.linalg import lapack_lite, _umath_linalg

&gt;  ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory


I am a newbie in i3 and I can't trace back this problem or relate it to i3 that why it's just happening there and not unity. I'd appreciate if I can have your suggestions.


</description><pubDate>Thu, 11 Sep 2014 15:36:51 +0000</pubDate><guid>https://faq.i3wm.org/question/4624/switching-from-unity-to-i3-causes-a-problem-with-a-python-package/</guid></item><item><title>Comment by Adaephon for &lt;p&gt;I have used virtualenv to create a local installation of python and some packages(numpy) are bound to some shared object (OpenBlas) compiled and linked locally. It works perfectly when I use unity in ubuntu 14.04 but when I switch to i3 I receive this error message:&lt;/p&gt;

&lt;blockquote&gt;
  &lt;p&gt;from numpy.linalg import lapack&lt;em&gt;lite, _umath&lt;/em&gt;linalg&lt;/p&gt;
  
  &lt;p&gt;ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory&lt;/p&gt;
&lt;/blockquote&gt;

&lt;p&gt;I am a newbie in i3 and I can't trace back this problem or relate it to i3 that why it's just happening there and not unity. I'd appreciate if I can have your suggestions.&lt;/p&gt;
</title><link>https://faq.i3wm.org/question/4624/switching-from-unity-to-i3-causes-a-problem-with-a-python-package/?comment=4681#comment-4681</link><description>It looks as if there is a difference in the library search paths between Unity and i3. Most likely it is some environment setting. Is `LD_LIBRARY_PATH` or `LD_RUN_PATH` set (differently) when using Unity? </description><pubDate>Thu, 25 Sep 2014 07:20:24 +0000</pubDate><guid>https://faq.i3wm.org/question/4624/switching-from-unity-to-i3-causes-a-problem-with-a-python-package/?comment=4681#comment-4681</guid></item></channel></rss>